### PR TITLE
Implement status command

### LINKED ISSUE #30: List status of all local repos [matching pattern X]
Command: `dadmin status -o <org> -r <regex>`

### PR DESCRIPTION
**Pull request by lenguyenthanh**
Close #30 

## Usage

`dadmin status -o <org> -r <regex> --verbose`

## Effect

This command will try to show statuses of all local repositories that match a regex pattern.

## Output

With `--verbose` flag
```
Status for repos in org dadmin-test

+----------------------------------------------------+
| Repo                branch        ±origin  U D M C |
+====================================================+
| test-1              master        2        1 1 1 0 |
| U new-changelog.md                                 |
| D changelog.md                                     |
| M README.md                                        |
| ----                                               |
| private-test-2      master        0        0 0 0 0 |
| test-2              master        0        0 0 0 0 |
| private-test-1      thanh-branch  0        0 0 0 0 |
| =====                                              |
| Total                             1        1       |
+----------------------------------------------------+

```

Without `--verbose` flag
```

Status for repos in org dadmin-test

+------------------------------------------------+
| Repo            branch        ±origin  U D M C |
+================================================+
| test-1          master        2        1 1 1 0 |
| private-test-2  master        0        0 0 0 0 |
| test-2          master        0        0 0 0 0 |
| private-test-1  thanh-branch  0        0 0 0 0 |
| =====                                          |
| Total                         1        1       |
+------------------------------------------------+

```

### CODE REVIEW

**Comment by snomos** [comment]
The compact / non-verbose view should be more compact. What I had in mind was something like this:

```
Status for repos in org: dadmin-test
Repo           ±origin U D M
============================
test-1         +2      1 1 1
private-test-2  0      0 0 0
test-2          0      0 0 0
private-test-1  0      0 0 0
============================
Total                  1 1 1
============================
```

My main use case is to use it as a check to see that merges or oder modifications across many repos have gone well. If the operation succeeded, the number of changes in each repo should be the same, and thus such a tabular overview will immediately highlight repos that need a more thorough check.

All columns must be aligned, the repo name left-aligned, the other columns right-aligned.

**Comment by lenguyenthanh** [comment]
Ok, I understand now, I'll work on that.

Do you have any thought on verbose version?

One thing that you mentioned in #30 is showing diff. But I think showing the diff is quite complicated, and if we want we can make a diff command later.

**Comment by snomos** [comment]
> Do you have any thought on verbose version?

Probably list filenames for modified files, something like:

```
test-1         +2      1 1 1
U file1
D file2
M file3
```

> One thing that you mentioned in #30 is showing diff. But I think showing the diff is quite complicated, and if we want we can make a diff command later.

Agree, skip it for now.

**Comment by lenguyenthanh** [comment]
@snomos Just updated the output on the description. Can you please check it?

**Comment by snomos** [comment]
Latest version looks good for now, further refinements will have to wait until it has been used a bit more, except one thing: maybe there should be a column for added (A) files?

**Comment by lenguyenthanh** [comment]
`U` means means untracked files also means added files.
> except one thing: maybe there should be a column for added (A) files?

And other letter meaning:
`D`: Deleted
`M`: Modified
`C`: Conflicted

**Comment by lenguyenthanh** [comment]
@snomos, I think I misunderstood you. This command now is definitely need a column for added files.
`U` only means untracked files.

**Pull request merged**
