### PR TITLE
Create new reposiotory

### PR DESCRIPTION
**Pull request by lenguyenthanh**
Address issue #34 

The command looks like: `cargo run -- create repo -o <org> -r <regex> -d <dir> --public --use-https --no-push`

This is a working-in-progress pr. It is 70 percent done.

Below, I will describe how it works:

Step 1: Pick the parent directory, parent directory is specified by `-d` option or otherwise `dadmin_root/{org}` directory.

Step 2: scan all directories inside the parent directory and filter directories that match `regex`

Step 3: for `dir` in filtered_directories do

Step 4: Check if `dir` is a git repository

Step 5a: Check if the repository has a remote named: origin then return and print error message.

Step 5: create new repository in organization `org` with name of `dir`

Step 6: Set remote origin of `dir` by the new created repository

Step 6: Push all to origin.

### CODE REVIEW

**Comment by lenguyenthanh** [comment]
@snomos Please review if I'm implementing correct behavior.

I also changed command argument a bit. New created repositories will be private by default. Use `--public` flag if we want it public.

I think private by default is a bit safer, especially when we push like multiple repositories at one time.

**Comment by snomos** [comment]
The logic seems fine, but I am a bit unsure of the last step:

> Step 6: Push all to origin.

I had imagined that as an independent command, but maybe there's no reason to. One could leave it as you suggest, but add an option to NOT push (ie pushing is default).

Making private by default is probably the safest option, I agree.

**Comment by lenguyenthanh** [comment]
> add an option to NOT push (ie pushing is default).

I'll add this option.

**Comment by lenguyenthanh** [comment]
> This might imply a function to make a repo public, but I think those cases are so rare that we can deal with them manually using the GitHub web interface — I don't think we'll see massive changes of repos from private to public, since most repos will be public in the first place.
> That is: not needed, and now also documented why I don't think we need a function to change a repo from private to public or the other way around.

Hey @snomos, I think it's better to discuss this `create repo` command here. 

I'm not sure I understand your comment. Could you please explain a bit more?

**Comment by snomos** [comment]
> Hey @snomos, I think it's better to discuss this `create repo` command here.

Ok.

> I'm not sure I understand your comment. Could you please explain a bit more?

I thought we need a function to convert a repo from private to public, but then realised that there are so few cases that we can use the standard github web GUI for that. So we should not spend hours making such a function.

**Comment by lenguyenthanh** [comment]
So here is the final command: `cargo run -- create repo -o <org> -r <regex> -d <dir> --public --use-https`

I added support for `use-https` to make our tool consistent.

I also added a step: `Step 5a: Check if the repository has a remote named: origin then return and print error message.`.

This step is to avoid trying to create a new repository for an already exist one.

**Comment by snomos** [comment]
> I also added a step: `Step 5a: Check if the repository has a remote named: origin then return and print error message.`.
> 
> This step is to avoid trying to create a new repository for an already exist one.

Very nice! 👍

**Comment by lenguyenthanh** [comment]
This is actually the final command: `cargo run -- create repo -o <org> -r <regex> -d <dir> --public --use-https --no-push`

I almost forgot `--no-push` option.

I you agree I'll merge this PR to master after all checks pass.

**Comment by snomos** [comment]
> I you agree I'll merge this PR to master after all checks pass.

I agree 👍

**Pull request merged**
